package com.jht.nvntry.catalog;

import com.jht.nvntry.catalog.model.Product;
import com.jht.nvntry.catalog.model.request.CreateProductRequest;
import com.jht.nvntry.catalog.model.request.PatchProductRequest;
import com.jht.nvntry.catalog.model.response.ProductResponse;
import com.jht.nvntry.shared.exception.ConflictException;
import com.jht.nvntry.shared.exception.ResourceNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Best Practices for Spring Boot Unit Tests:
 * 1. Use @ExtendWith(MockitoExtension.class) to enable Mockito annotations (@Mock, @InjectMocks).
 * 2. Use @Nested classes to group tests by method or behavior (e.g., "create", "getById").
 * 3. Use @DisplayName for readable test reports that explain business intent.
 * 4. Mock only dependencies (Repositories), not the class under test.
 * 5. Verify interactions (verify()) to ensure side effects (like save) happen exactly as expected.
 * 6. Use ArgumentCaptor to inspect objects passed to mocks if you need to assert internal state changes.
 * 7. Test both happy paths and failure paths (exceptions).
 */
@ExtendWith(MockitoExtension.class)
public class CatalogServiceTest {

    @Mock
    private ProductRepository productRepository;

    @InjectMocks
    private CatalogService catalogService;

    private UUID productId;
    private CreateProductRequest createRequest;
    private Product savedProduct;

    @BeforeEach
    void setUp() {
        productId = UUID.randomUUID();
        createRequest = new CreateProductRequest(
                "TEST-SKU",
                "Test Product",
                Product.UnitOfMeasure.EACH
        );
        // Simulate the product as it would exist in the DB after creation
        savedProduct = aProduct("TEST-SKU");
        // Use reflection or a test-only setter if ID is generated by DB/JPA,
        // but for unit tests we often just mock the return value of save()
    }

    @Nested
    @DisplayName("Get Product by ID/SKU or list all active")
    class GetProductTests {

        @Test
        @DisplayName("Should return product when found by ID")
        void returnsProductWhenFoundById() {
            when(productRepository.findById(productId)).thenReturn(Optional.of(savedProduct));

            ProductResponse result = catalogService.getById(productId);

            assertThat(result.id()).isEqualTo(savedProduct.getId());
        }

        @Test
        @DisplayName("Should return product when found by SKU")
        void returnsProductWhenFoundBySku() {
            when(productRepository.findBySku("TEST-SKU")).thenReturn(Optional.of(savedProduct));

            ProductResponse result = catalogService.getBySku("TEST-SKU");

            assertThat(result.id()).isEqualTo(savedProduct.getId());

            verify(productRepository, times(1)).findBySku("TEST-SKU");
        }

        @Test
        @DisplayName("Should return empty Page when no active products exist")
        void returnsEmptyWhenNoActiveProducts() {
            Pageable pageable = PageRequest.of(0, 20);
            Page<Product> emptyPage = Page.empty(pageable);

            when(productRepository.findAllActive(pageable)).thenReturn(emptyPage);

            Page<ProductResponse> result = catalogService.listActive(pageable);

            assertThat(result.isEmpty()).isTrue();
            assertThat(result.getTotalElements()).isEqualTo(0);

            verify(productRepository).findAllActive(pageable);
        }

        @Test
        @DisplayName("Should return mapped Page when active products exist")
        void returnsPageWhenActiveProductsExist() {
            Pageable pageable = PageRequest.of(0, 20);
            Product product = aProduct("SKU-1");
            Page<Product> productPage = new PageImpl<>(List.of(product), pageable, 1);

            when(productRepository.findAllActive(pageable)).thenReturn(productPage);

            Page<ProductResponse> result = catalogService.listActive(pageable);

            assertThat(result).isNotNull();
            assertThat(result.getContent()).hasSize(1);
            assertThat(result.getContent().getFirst().sku()).isEqualTo("SKU-1");

            verify(productRepository).findAllActive(pageable);
        }

        @Test
        @DisplayName("Should throw ResourceExceptionNotFound when product not found by ID")
        void throwsWhenProductNotFoundById() {
            when(productRepository.findById(productId)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> catalogService.getById(productId))
                    .isInstanceOf(ResourceNotFoundException.class);
        }

        @Test
        @DisplayName("Should throw ResourceExceptionNotFound when product not found by SKU")
        void throwsWhenProductNotFoundBySku() {
            when(productRepository.findBySku("TEST-SKU")).thenReturn(Optional.empty());

            assertThatThrownBy(() -> catalogService.getBySku("TEST-SKU"))
                    .isInstanceOf(ResourceNotFoundException.class);

            verify(productRepository, times(1)).findBySku("TEST-SKU");
        }
    }

    @Nested
    @DisplayName("Create Product")
    class CreateProductTests {

        @Test
        @DisplayName("Should create product when SKU is unique")
        void shouldCreateProductWhenSkuIsUnique() {
            // Arrange
            when(productRepository.existsBySku("TEST-SKU")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(invocation -> invocation.getArgument(0));
            // Act
            ProductResponse response = catalogService.create(createRequest);
            // Assert
            assertThat(response).isNotNull();
            assertThat(response.sku()).isEqualTo("TEST-SKU");
            // Verify interactions
            verify(productRepository, times(1)).existsBySku("TEST-SKU");
            verify(productRepository, times(1)).save(any(Product.class));
        }

        @Test
        void shouldThrowConflictExceptionWhenSkuExists() {
            // Arrange
            when(productRepository.existsBySku("TEST-SKU")).thenReturn(true);
            // Act & Assert
            assertThatThrownBy(() -> catalogService.create(createRequest))
                    .isInstanceOf(ConflictException.class)
                    .hasMessageContaining("TEST-SKU");
            // Verify save was NEVER called
            verify(productRepository, never()).save(any(Product.class));
        }
    }

    @Nested
    @DisplayName("Update Product Name")
    class UpdateProductNameTests {

        @Test
        @DisplayName("Should update name and rely on dirty checking")
        void updateNameAndFlushOnCommitDoesNotCallSave() {
            PatchProductRequest patchRequest = new PatchProductRequest("Updated Name");
            when(productRepository.findById(productId)).thenReturn(Optional.of(savedProduct));

            ProductResponse result = catalogService.updateName(productId, patchRequest);

            assertThat(result.name()).isEqualTo("Updated Name");
            // Critical: save() should not be called
            verify(productRepository, never()).save(any(Product.class));
        }

        @Test
        @DisplayName("Should throw ResourceNotFoundException if product does not exist")
        void shouldThrowExceptionIfProductNotExists() {
            when(productRepository.findById(productId)).thenReturn(Optional.empty());
            PatchProductRequest patchRequest = new PatchProductRequest("Updated Name");

            assertThatThrownBy(() -> catalogService.updateName(productId, patchRequest))
                    .isInstanceOf(ResourceNotFoundException.class);

            verify(productRepository, never()).save(any(Product.class));
        }
    }

    @Nested
    @DisplayName("Deactivate Product")
    class DeactivateProductTests {

        @Test
        @DisplayName("Should set active to false and rely on dirty checking")
        void shouldUpdateActive() {
            when(productRepository.findById(productId)).thenReturn(Optional.of(savedProduct));

            catalogService.deactivate(productId);

            assertThat(savedProduct.isActive()).isFalse();
            // Critical: save() should not be called
            verify(productRepository, never()).save(any(Product.class));
        }
    }

    private Product aProduct(String sku) {
        return Product.create(sku, "Test Product", Product.UnitOfMeasure.EACH);
    }
}