### Get All Products
GET {{baseUrl}}/products
Accept: application/json

### Get single product
GET {{baseUrl}}/products/a5555555-5555-5555-5555-555555555555
Accept: application/json

### Create single product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "sku": "VTUBER-111",
  "name": "Botan"
}

### Update single product
PATCH {{baseUrl}}/products/948fc070-2e10-4044-95f2-707c672785d8
Content-Type: application/json

{
  "name": "Azki"
}

### Reserve
POST {{baseUrl}}/products/{{checkPID}}/reservations?locationId={{checkLID}}
Content-Type: application/json

{
  "quantity": 100
}