### Get All Products
GET {{baseUrl}}/products
Accept: application/json

### Get single product
GET {{baseUrl}}/products/c503ec2f-c6a7-44bf-a246-bc10f7af05cc
Accept: application/json

### Create single product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "sku": "VTUBER-212",
  "name": "Koyori"
}

### Update single product
PATCH {{baseUrl}}/products/64bcdaab-0f94-4a82-8751-2ce96854345e
Content-Type: application/json

{
  "name": "Subaru"
}

### Check availability
GET {{baseUrl}}/products/d4e5f6a7-b8c9-0123-defa-234567890123/inventory?location=11111111-1111-1111-1111-111111111111