### Actuator Health
GET {{baseUrl}}/actuator/health

## Products
### Get by product id
GET {{baseUrl}}/v1/products/ef2e7b05-eef0-47db-a376-22a3c99756ee
Accept: application/json

### Get by product sku
GET {{baseUrl}}/v1/products/sku/VTUBER-112
Accept: application/json

### List all active products
GET {{baseUrl}}/v1/products?page=0&size=20&sort=createdAt
Accept: application/json

### Create single product
POST {{baseUrl}}/v1/products
Content-Type: application/json

{
  "sku": "VTUBER-112",
  "name": "Botan",
  "unit_of_measure": "EACH"
}

### Update single product
PATCH {{baseUrl}}/v1/products/a1b2c3d4-e5f6-7890-abcd-ef1234567890/name
Content-Type: application/json

{
  "name": "Business Laptop Pro 15 inch"
}

### Deactivate single product
DELETE {{baseUrl}}/v1/products/9f39b18a-322f-45a2-8a6a-29f7efbbd70e

## Inventory
### Movements
POST {{baseUrl}}/v1/inventory/movements
Content-Type: application/json

{
  "product_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  "movement_type": "ADJUST",
  "quantity_delta": 1,
  "reason_code": "SYSTEM_CORRECTION",
  "reference_id": "cccccccc-cccc-cccc-cccc-cccccccccccd",
  "reference_type": "",
  "idempotency_key": "sys-2024-002-vtuber",
  "created_by": "system",
  "note": "Discovered from the wild"
}